[package]
name = "payment_escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.2"
ic-cdk = "0.7.0"
ic-cdk-macros = "0.6.0"
serde = "1.0.152"
serde_derive = "1.0.152"
